### ISSUE TITLE
Would it be wiser to check lsb_release first?

### ISSUE THREAD

**Issue by wolfeidau** [wblankenship/getos#15]
It may be good to try lsb_release before looking in files.

eg from ubuntu

```
root@buildbox01:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty
```

Just a thought.

**Comment by rvagg** [comment]
it's active on so few configurations by default that it's almost worthless, in my experience anyway, plus the overhead of the child process is way more than file reads. It'd be nice if it was consistent though.

**Comment by wolfeidau** [comment]
Yeah just a thought, pretty sad this is the only way to recognise an OS.

Child process is meh, but yeah inconsistencies would be a killer.

Interesting comparing how ansible does it. https://github.com/ansible/ansible/blob/4e854192577475bc8c75d97af0db237970508b0e/lib/ansible/module_utils/facts.py#L76-L458

**Comment by wblankenship** [comment]
@wolfeidau that is interesting! It turns out we can add the following in os.js assuming ansible is correct:

```
/etc/oracle-release: OracleLinux
/etc/vmware-release: VMwareESX
/etc/openwrt_release: OpenWrt
/etc/alpine-release: Alpine
```
It also might be useful to see how https://docs.python.org/2/library/platform.html#unix-platforms is doing it.
