### ISSUE TITLE
Possible improvements

### ISSUE THREAD

**Issue by wblankenship** [wblankenship/getos#16]
Continued from #15

https://github.com/ansible/ansible/blob/4e854192577475bc8c75d97af0db237970508b0e/lib/ansible/module_utils/facts.py#L76-L458

It turns out we can add the following in os.js assuming ansible is correct:

```
/etc/oracle-release: OracleLinux
/etc/vmware-release: VMwareESX
/etc/openwrt_release: OpenWrt
/etc/alpine-release: Alpine
```
It also might be useful to see how https://docs.python.org/2/library/platform.html#unix-platforms is doing it.

**Comment by wblankenship** [comment]
Closing as stale. Can reopen if useful.

**Comment by root-io** [comment]
```
> mongodb-prebuilt@4.5.5 postinstall /myproject/node_modules/mongodb-prebuilt
> node install.js

/myproject/node_modules/mongodb-download/index.js:80
				throw e;
				^

Error: No unique release file found!
    at /myproject/node_modules/getos/index.js:136:21
    at FSReqWrap.oncomplete (fs.js:82:15)

```

I guess Alpine linux is not yet supported ? :p
