### ISSUE TITLE
Detect whether we're running in a docker image

### ISSUE THREAD

**Issue by bcoe** [wblankenship/getos#4]
It would be useful if we detected whether or not getos was being run inside a Docker instance, and populated an additional variable:

http://stackoverflow.com/questions/20010199/determining-if-a-process-runs-inside-lxc-docker

Perhaps we could add a `container` variable that we attempt to populate with the type of VM an OS is running on? `vagrant`, `xen`, `docker`.

Thoughts?

**Comment by wblankenship** [comment]
Closing as stale. Can reopen if still useful. Thoughts are that this would be useful as a separate module.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/is-docker

**Comment by wblankenship** [comment]
@sindresorhus :heart:
